### ISSUE TITLE
Catalyst <-> Studio integration for Short form videos

### ISSUE THREAD

**Issue by gioelecerati** [livepeer/task-runner#130]
After a sync with @emranemran , some work is needed to be done on Studio Task Runner and Catalyst for short form videos, specifically:

- add `AutoMP4s: bool` in `api/vod` in both the request studio & the catalyst-api struct
- Add `Mp4Outputs` to TranscodeStatusMessage from Catalyst to Studio
- Potentially, before populating the struct of TranscodeStatusMessage check on the storage if the mp4 is there (may require more time)
- `api/transcode` endpoint need to recognize the AutoMP4s

**Comment by victorges** [comment]
> api/transcode endpoint need to recognize the AutoMP4s

Do you mean the [`POST /api/transcode` API](https://github.com/livepeer/livepeer-com/blob/b0349655ef4a92513ce1fe1a91f16bec21f383c4/packages/api/src/controllers/transcode.ts#L13) from Studio? 
If so, I don't think we should add MP4 outputs to that.

This is a playback optimization feature, and we don't handle playback on that API, instead just writing files to the user-provided object store. So we should also not start creating files that weren't explicitly requested for, or it can lead to additional storage usage for the users that never really requested for it (the contract today is only to request an HLS playlist).

When we do implement the Studio API support for example to override the generation of MP4s for assets, then I think it could make sense to add the support on the Transcode API as well (like the interfaces you proposed in the tech design).

WDYT?
